import { QuartzTransformerPlugin } from "../types"
import { Root, Paragraph } from "mdast"

export const AI: QuartzTransformerPlugin = () => {
  return {
    name: "AI",
    markdownPlugins() {
      return [
        () => {
          return (tree: Root, file) => {
            const ai = file.data.frontmatter?.ai as string | undefined
            if (!ai) return

            let aiText = ""
            if (ai === "checked" || ai === "refactored") {
              aiText = "Hand-crafted by Flo, auto-checked by AI."
            } else if (ai === "generated" || ai === "co-created") {
              aiText = "Parts of this page were be generated by AI."
            }

            if (!aiText) return

            // Find existing law-disclaimer paragraph
            let disclaimer = tree.children.find(
              (node): node is Paragraph =>
                node.type === "paragraph" &&
                (node.data?.hProperties as any)?.className?.includes("law-disclaimer"),
            )

            if (disclaimer) {
              // Add a space before appending the AI disclaimer
              disclaimer.children.push({ type: "text", value: " " + aiText })
            } else {
              // Create a new disclaimer paragraph if it doesn't exist
              disclaimer = {
                type: "paragraph",
                children: [{ type: "text", value: aiText }],
                data: {
                  hProperties: {
                    className: ["law-disclaimer"],
                  },
                },
              }
              tree.children.unshift(disclaimer)
            }
          }
        },
      ]
    },
  }
}
